env:
  browser: true
  commonjs: true
  es2021: true
extends:
  - google
  - prettier
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 12
plugins:
  - "@typescript-eslint"
rules: {}
